# post\.github\workflows\ci.yml

name: Service CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.3
        ports:
          - 3330:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: test
      POST_DATABASE_URL: mysql://root:root@127.0.0.1:3330/app_db

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Prisma generate (native engines)
        run: npm run prisma:generate

      - name: Reset DB and apply migrations
        run: node ./scripts/prisma.mjs migrate reset --force --skip-seed

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test (CI mode)
        run: npm run test:ci
